[package]
name = "pahi-olin"
version = "0.1.0"
authors = ["Christine Dodrill <me@christine.website>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmer-runtime = "0.13"
log = "0.4"
num-traits = "0.2"
num-derive = "0.2"
rand = "0.7"
